[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"
evm_version = "paris"  # Avoid PUSH0 opcode (Shanghai feature not supported by go-ethereum)

[rpc_endpoints]
shard0 = "http://localhost:8545"
shard1 = "http://localhost:8546"
shard2 = "http://localhost:8547"
shard3 = "http://localhost:8548"
orchestrator = "http://localhost:8080"
